name: PulseDropHead
version: '1.0'
main: ex.rizzve.pulseDropHead.PulseDropHead
api-version: '1.21'
authors: [rizzve]
website: https://github.com/ExRizzve
description: Player head drops plugin for Pulse 1.21.11+ - https://pulsemc.dev/

commands:
  pulsedrophead:
    description: PulseDropHead commands
    usage: /pulsedrophead <givehead|lang|reload>
    aliases: [pdh]